function [param,param_plot] = GetIniParam(~,~)
    param = struct( ...
... %%% Accessed a lot
        'DEBUGGING',0, ...              %%% Flag used for printing fitting values and plotting
        'PLOT_FLAG',0, ...              %%% Flag used to allow plotting at each fit
        'DIAGNOSE',0,...            %%% Only in cell-level info
        'DEBUG_Count',0,...
        'Use_Gradient',0,...
        'EM_Algorithm',0,...
        'ControlsCalib',0,...
        'sample_type',[],...
        'Prior_order',2,...
        'Averaging',0,...
        'Prior_truncated',0,...
        'N_points',0,...
        'Stain',0,...
        'Stain_Neurites',0,...
        'NormDivTau',1,...
        'clip_vector',1,...
        'idx_peak_thresh',9,...
        'clip_type',1,...
        'Mask_together', 1,...
        'Rerun_Mask',1,...
        'FixOldMasks',0,...
        'Rerun',1,...
        'folder_idx_current',1,...
        'Amp_Actual',3000,...
        'FoldersToRun',[],...
        'N_points_arr',[],...
        'tshift_flag',1,...
        'DCshift_flag',1,...
        'Scaleshift_flag',1,...
        'NameSTR',[],...
        'Analysis_type',1,...
        'NeighborsNoise_flag',0,...
        'PriorVector',[],...
        'PriorMask',[],...1
        'PriorCell',[],...
        'PriorType',[],...
        'PriorNaming',[],...
        'PriorData',[],...
        'Amp_save',[],...
        'AmpMap',[],...
        'AmpEst_flag',0,...
        'order_map',[],...
        'sigma_prior',0.1,...
        'sigma_prior_amp',0.03,...
        'randPrior',false,...
        'SweepCostfn',0,...
        'Method',9, ...                 %%% Fitting method: 1) LMS, 2) Gaussian MLE with thermal noise, 3) MLE Poission, 4) MLE Gauss, 5) MLE Gauss with Chi^2/4 6) Emperical Noise Model
        'order',1, ...                  %%% Fitting order
        'laser','SP',...                %%% Laser used for selection of appropriate IRF, write 'SP' or 'NKT'
        'IRF_1D',1,...
        'SolveMatrix',0,...
        'segments',0, ...               %%% Flag used to do segment fitting, used as a prior if pixelwise is also active
        'N_neighbors',12,...
        'taper_tau_lower',0.5,...
        'taper_tau_upper',6,...
        'taper_tau_const_lower',1.2,...
        'taper_tau_const_upper',1.5,...
        'taper_tau_reg_factor_lower',50000,...
        'taper_tau_reg_factor_upper',100,...
        'taper_tl',0.5,...
        'taper_tu',6,...
        'after_peak',0,...
        ...% 'Ataper_reg',10000,...
        'Ataper_reg',0,...
        'taper_regl',20000,...
        'taper_regu',100,...
        'fixed_amp',0,...
        'fixed_amp_arr',[],...
        'fixed_amp_prior',0,...
        ...
        'taper_amp_limit',0.4,...
        'taper_amp_const',200,...
        'taper_amp_reg_factor',1.5,...
        ...
        'RegFactor1',1,...
        'RegFactor_amp',1,...
        'NoiseActual_params',[1 2],...
        ...
        'NoiseVersion',16,...
        'NoiseFileName',"Int_var_out_empirical",...
        'KMeansSeg',3,...
        'Current_Prior',0,...
        'DCShift',205,...
        ... %%% EM Stuff
        'type', "exp",...
        'f_damping', 0.2,...
        'R_damping', 0.1,...
        'ini_damping', 0.5,...
        'lambda_spatial', [0,0,0,0,0,0,0],...
        'lambda_prior', [2,2,2,2,2,2,2],...   % 0 = ignore EM prior, larger = stronger pooling
        'min_var_z', 0.05,... % Corresponds to a small uncertainty in latent space
        'sigma0_vec', [2 2 1 1 1 0.01 0.01],... % in z-units
        'N_iter', 5,...
        'trim_prct', 90,...
        'ell_spatial', 2,...
        'sigma_anchor_vec', [6; 6; 4; 4; 4; 10; 10],...  % [z_tauUA z_tauBA zBM zUA zBA z_rhob z_rhoc]
        'lambda_anchor', [0.1,0.1,0.1,0.1,0.1,0.1,0.1],...  % [z_tauUA z_tauBA zBM zUA zBA z_rhob z_rhoc]'
... %%% Simulation flags
        'PLOT_Freq',0, ...              %%% Flag used During Debug, plot the frequency domain signal
        'PLOT_Tau',0, ...               %%% Flag used During Debug, plot the frequency domain signal
        'testtau',0, ...                %%% Unavailable now, runs fitting 1000 times and draw histogram
        'SHOW_ONLY',0, ...              %%% For internal use only. Flag used for skipping analysis and saving of fig
... %%% Parameters for processing the data
        'THRESHOLD',[], ...             %%% Threshold value used. Only used in saving file name since the mask is used for filtering
        'BIN',1, ...                    %%% Used if extra binning is allowed
        'ROI',[], ...                   %%% Region of interest for fit.
        'Mask',[], ...                  %%% Mask used for fitting. Will ignore fitting anything that is not in the mask. Used to identify objects
        'Label_Mask',[],...
... %%% main Fitting parameters
        'pixelwise',1, ...              %%% Flag used to do pixel wise fitting
        'cell_level_analysis',0,...
        'sigma_max',0.5, ...           %%% Max allowed standard deviation
        'mainlb',0, ...                 %%% Lifetime lower bound
        'mainub',7, ...                 %%% Lifetime ubber bound
        'mainIC',2, ...                 %%% Lifetime Initial condition
        'tau_vec',0:0.01:10, ...      %%% Lifetime vector used in Taper, and for plotting distribution, affect speed significantly in continouous fitting
        'amp_vec',0:0.01:1,...
        'nonlcon',1,...                 %%% Use nonlinear constrains between lifetimes
        'time_before',0,...             %%% Time before the rise time
        'SubDrk',0,...
... %%% Parameters to be used during simulation, can be separated for efficieny
        'lb',1e-5, ...                   %%% Lifetime lower bound temp for when a prior is used
        'ub',7, ...                    %%% Lifetime ubber bound temp for when a prior is used
        'amplb',0,...
        'ampub',1,...
        'IC',2, ...                   %%% Lifetime Initial condition for when a prior is used
        'err',0, ...                    %%% Used to mark if there is an error in the current fit        
        't_shift_max', 0.5,...         %%% Maximum range for shif tin bounds
        'amp_ratio_max', 0.15,...       %%% Maximum range for shif tin bounds
        'y_shift_max', 5,...            %%% Maximum range for shif tin bounds
        'tau_dist',[], ...              %%% The current lifetime distribution. Used in both discrete and continouous
        'Trials',1, ...                 %%% Not used, number of times the fitting is ran until good fit is reached
        'prior',[], ...                  %%% Decide whether a prior is used or not
        'prior_tau',[], ...                  %%% Decide whether a prior is used or not
        'N_seg',0,...                   %%% Number of segments averaged. Used for estimating noise
... %%%%% ...
        'global',0  ,...                  %%% Global or local analysis during fitting
        'parallel',1, ...               %%% Use parllel processing, currently only 1 available
        'cont',0, ...                   %%% Continuous or discrete lifetime fitting
        'cont_type',1, ...              %%% Type of continious lifetime distribution used 1) Gaussian, 2) Gamma, 3) Inverse gamma, 4) Log-normal    
        'MCP',[],...                    %%% Automatically read from the file and replaced during the running of the code
        'gain_ratio',[],...
        'MCPNoise',[],...               %%% MCP Noise factor array, used in fitting
        'IRF_dt',50);                   %%% Set the dt of the IRF you want to use
    
    %%% Final plot parameters
    param_plot = struct( ...
        'plot_flag',1,...               %%% Flag whether to report or not
        'figformat','.png',...          %%% 1) .fig, 2) .png
        'SaveInFolder',0,...            %%% For saving results plots in the respective folder name similar to the data 1) yes, 0) no
        'hbins_tau', 0:0.005:10, ...   %%% Histogram bins used for calculating the results
        'hbins_chi', 0:0.01:100, ...   %%% Histogram bins used for calculating the results
        'hbins_amp', 0:0.001:1, ...   %%% Histogram bins used for calculating the results
         ...%%% Types of plots to be generated and saved
        'plot_mix',0, ...               %%% Plot all All info
        'plot_chi',0, ...               %%% Plot Chi
        'plot_ObjHist',0, ...           %%% Plot all All info
        'plot_hist_style','plot',...
        'delta_line',0,...
        'Save_colorbar',0, ...          %%% Plot all All info
        'plot_PeakInt',0, ...           %%% Plot Peak Intensity image
        'plot_PeakLT',0, ...            %%% Plot Peak intensity and Lifetime overlay
        'plot_hist',0, ...              %%% Plot Histogram
        'plot_ITau',0,...
        'plot_Colocalize',0,...
        'fig_idx',2,...
        'custom_plots',0, ...           %%% Plot Chi
        'Save_maps',0, ...              %%% 0) to use chi, 1) save chi maps
        'Stack_figure',1,...            %%% Only in plotting Histogram Images
        'scale_bar',20,...              %%% length of scale bar in micrometers
        'scale_Left_or_right',2,...     %%% 1) Left 2) Right
        'scale_bar_Linewidth',5,...     %%% Scale bar linewidth
        'Magnification',40, ...         %%% Magnification used, for plotting scale bar.
        'Fit_Histogram',1,...           %%% Fit the histogram to gaussian on the plot
        'Crop_plot',1,...               %%% Cropping the output plot, 0) No crop. 1) Manual Crop (Using Img_xlim_min to set the cropping bounds) 2) Automatic crop
        'crop_dxmin', 50, ... 
        'crop_dymin', 50, ...
        'crop_dxmax', 50, ...
        'crop_dymax', 50, ...
        'clim_tau_min', 2.7, ...
        'clim_tau_max', 3, ...
        'hist_xlim_min', 0, ...
        'hist_xlim_max', 4, ...
        'clim_I_min', 0.05, ...
        'clim_I_max', 0.7, ...
        'Img_xlim_min',200,...
        'Img_xlim_max',800,...
        'Img_ylim_min',0,...
        'Img_ylim_max',600,...         %%% Maximum default is 608
        'N_points_marker',10,...
        'CRB_on_LT',0,...
        'plot_AutoObjStats',0,...
        'fontsz',40);                   %%% Font size used in plots
end

%%% DEBUGGING flag: enables debugging mode if DEBUGGING = 1
%%% In debugging mode: 
% 1) No try-catch statement, errors will show
% 2) Fitted lifetime will be plotted for each point and the simulation will
% pause afterwards
% 3) Only the Region of interest will be analyzed. You can use this mode to
% pinpoint a specific group of pixels for debugging
% ROI WORKS AS FOLLOWS: [ymin, ymax, xmin, xmax]
% keyboard
